name: Build the plug-in
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  build_the_plug-in:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install lv2
        run: sudo apt-get install -y lv2-dev
      - name: Checkout libsndfile
        uses: actions/checkout@v4
        with:
          repository: 'libsndfile/libsndfile'
          ref: '1.2.2'
          path: 'libsndfile'
      - name: Build libsndfile
        run: cd libsndfile && mkdir CMakeBuild && cd CMakeBuild && cmake .. && make && cd
      - name: Install libsndfile
        run: cd libsndfile/CMakeBuild && sudo make install && cmake --build . && sudo ldconfig && cd
      - name: Checkout lsp-tk
        uses: actions/checkout@v4
        with:
          repository: 'lsp-plugins/lsp-tk-lib'
          ref: '1.0.19'
          path: 'lsp-tk-lib'
      - name: Build lsp-tk-lib
        run: cd lsp-tk-lib && make config && make fetch && make compile && cd
      - name: Install lsp-tk-lib
        run: cd lsp-tk-lib && sudo make install && sudo ldconfig && cd
      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          meson-version: 1.0.0
          ninja-version: 1.11.1
      - name: Test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: --verbose
          meson-version: 1.0.0
          ninja-version: 1.11.1
      - run: echo "The job's status is ${{ job.status }}."
