name: Build the plug-in
on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
      - 'improve-project-structure-and-setup'
jobs:
  build_the_plug-in:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: meson build
        run: |
          cd ${{ github.workspace }}
          meson build
      - name: meson test
        run: |
          cd ${{ github.workspace }}
          meson test
      - name: meson test
        run: |
          cd ${{ github.workspace }}
          meson dist
      - run: echo "The job's status is ${{ job.status }}."