name: Build the plug-in
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  build_the_plug-in:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install dependencies
        run: sudo apt-get install -y lv2-dev libx11-dev libxorg-dev libxt-dev libcairo2-dev
      - name: Clone submodules (BWidgets and friends)
        run: git submodule update --init --recursive
      - name: Compile dependencies
        run: make -C src/BWidgets bwidgets
      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          meson-version: 1.0.0
          ninja-version: 1.11.1
      - run: echo "The job's status is ${{ job.status }}."