name: Build the plug-in
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  build_the_plug-in:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install lv2
        run: sudo apt-get install -y lv2-dev
      - name: Retrieve pugl submodule
        run: mkdir -p subprojects ; cd subprojects ; git submodule add git@github.com:lv2/pugl.git ; cd ..
      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          meson-version: 1.0.0
          ninja-version: 1.11.1
      - name: Test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: --verbose
          meson-version: 1.0.0
          ninja-version: 1.11.1
      - run: echo "The job's status is ${{ job.status }}."
